### ISSUE TITLE
Unable to use basic auth

### ISSUE THREAD

**Issue by bcardiff** [instedd/ruby-resource_map_api_client#2]
The following snipet fails

``` ruby
api = ResourceMap::Api.basic_auth(email, password, resmap_host, use_https)
api.collections.all
```

```
NoMethodError: undefined method `status' for #<String:0x0055c08a4d2330>
    from /usr/local/bundle/bundler/gems/ruby-resource_map_api_client-7681243c48e3/lib/resource_map/api.rb:51:in `process_response'
    from /usr/local/bundle/bundler/gems/alto_guisso-9f1cf1b1d436/lib/guisso/api.rb:102:in `get'
    from /usr/local/bundle/bundler/gems/alto_guisso-9f1cf1b1d436/lib/guisso/api.rb:139:in `json'
    from /usr/local/bundle/bundler/gems/ruby-resource_map_api_client-7681243c48e3/lib/resource_map/collection_relation.rb:10:in `all'
    from (irb):6
    from /usr/local/bin/irb:11:in `<top (required)>'
```

RestClient used by `Guisso::Api::BasicAuth` and the httpclient of `Guisso::Api::Oauth` does not obey the same interface.

**Comment by bcardiff** [comment]
issue related instedd/alto_guisso#7
